env:
  browser: false
  es2021: true
  jest: true
  node: true
plugins:
  - jest
  - '@typescript-eslint'
extends:
  - standard
  - plugin:node/recommended
  - plugin:jest/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
rules:
  node/no-unsupported-features/es-syntax:
    - error
    - ignores: [modules]
